### ISSUE TITLE
Switch to kind of sleep-mode by changing Tsetpoint

### ISSUE THREAD

**Issue by KoelnSolar** [absalom-muc/MHI-AC-Ctrl#176]
detailed system description see issue #172 

**Describe the bug**
When I tried to figure out, if its possible to set a kind of "sleep-mode" like in Heat:Eco:no_movement_for1h(AC sets Tsetpoint to 15.0) or NIGHT/SETBACK (AC sets Tsetpoint to 10.0), I made the finding, that at least its possible to set Tsetpoint to 5.0 which reacts in OpData_Tsetpoint = 7.0. The AC stops like in the 2 described configurations and we've a kind of sleep mode.

I need such a sleep mode because I like to consume more solar energy than current energy consumption of AC. 
When there is more energy produced than consumed, I raise the Tsetpoint step-by-step 1 degree up to 3 degrees. With sundown(total consumption less production) same in the other direction. Result is a more or less overheated room. Problem is, that the AC now clocks frequently. In that situation I like to set it into a "sleep-mode" until the separately measured room temperature is reached.

**Comment by glsf91** [comment]
I don't understand what the question is but it looks like you want to let the AC consume more power when your have too much solar energy (and producing more heat then needed at that moment).
Instead of messing around with the setpoint (with strange values mentioned) you can also increase the Troom. When Troom is higher then (normal) setpoint the AC will also go in standby.
Of course only if you don't use the AC internal temperature sensor.
