### ISSUE TITLE
No issue, just a question

### ISSUE THREAD

**Issue by coyote1** [absalom-muc/MHI-AC-Ctrl#2]
Hey,
it's nice to see that someone has taken on the project again.
At the moment I am still using rjdekker's version, which works so far, but I would also like to test your solution with the Wemos Mini.
Where do you order your board? In Germany?
I also found something in China, but I would need a Gerber file instead of the Eagle file. Can you maybe also provide a Gerber file?

**Comment by absalom-muc** [comment]
I ordered the PCB in Germany. It was simple for me because they accept an Eagle file and they are fast (but of course more expensive). I created now the [Gerber files ](https://github.com/absalom-muc/MHI-AC-Ctrl/files/4082769/CAMOutputs.zip), but since I've no experience with this, I strongly recommend that you have a close look on the files before you issue an order based on these files.
Good luck!

**Comment by coyote1** [comment]
Thank you.
Do you have a link, where you ordered your circuit boards

**Comment by absalom-muc** [comment]
[https://www.eurocircuits.de/](https://www.eurocircuits.de/)

**Comment by absalom-muc** [comment]
Please consider the updated [Hardware.md](https://github.com/absalom-muc/MHI-AC-Ctrl/blob/master/Hardware.md) description! I added some useful information related to the connection of the AC and the remote control PCB.
