### ISSUE TITLE
Jumpers?

### ISSUE THREAD

**Issue by hvorragend** [absalom-muc/MHI-AC-Ctrl#31]
Could you please answer me for what purpose are the jumpers on the PCB?

Thank you very much

**Comment by absalom-muc** [comment]
There is one jumper JP1. It connects the voltage output of the DC/DC converter to the voltage input of the ESP8266 board. Originally I planned it because I feared problems if the ESP8266 is supplied simultaneously via the DC/DC converter and during test / debug via USB. But I have never seen a problem with it.
You can replace the jumper by a piece of wire.

**Comment by hvorragend** [comment]
What do you think? Should't this be located in the Wiki?

**Comment by absalom-muc** [comment]
Yes, I added a comment to [Hardware.md](https://github.com/absalom-muc/MHI-AC-Ctrl/blob/master/Hardware.md)

**Comment by hvorragend** [comment]
Thank you
