### ISSUE TITLE
Possible to add PIR function?

### ISSUE THREAD

**Issue by sacy80** [absalom-muc/MHI-AC-Ctrl#78]
Hi thank alot for the work. i try and it work. but i not good at coding. would like to know possible to add pir as a binary sensor to sent mqtt messages ?

very sorry, took your pcb design and change abit. 
https://1drv.ms/u/s!Ait4O1a98isBgYgazJgTbZKurobcyw?e=mjVgwO

**Comment by absalom-muc** [comment]
short answer: Yes, should be possible

Usually you find in the web examples for many different sensors connected to ESP8266 and used with MQTT

**Comment by sacy80** [comment]
ar, ao ijust add everyting in void loop ?  very sorry to ask about this.

**Comment by absalom-muc** [comment]
yes, in the loop() you read your PIR status and you publish the status with e.g. 
`MQTTclient.publish("topic", "data", true); `
Please check the PubSubClient documentation for details

**Comment by sacy80** [comment]
ok. noted. i try to figure out.. thanks alot for info and help :)

**Comment by sacy80** [comment]
![image](https://user-images.githubusercontent.com/30169265/152099757-86153fb4-1019-4b34-8aca-f97177a4536f.png)
Thanks alot for the info :) look like working :)

**Comment by absalom-muc** [comment]
you could simplify the code:
replace
![grafik](https://user-images.githubusercontent.com/23119513/152216193-90b857df-0a78-45a4-bc85-a22bd2214cb2.png)
by
![grafik](https://user-images.githubusercontent.com/23119513/152216252-af058815-3602-439d-97ae-729f8caa351f.png)
Since you are doing the same in both branches you don't need the if-clause

**Comment by sacy80** [comment]
oh.. i try. .. thanks for the help :)
